import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <header>
        <nav>
<img/>
<a href='/'>Home</a>
  <a href='/events'>Events</a>
<a href='/about-us'>About</a>
        
        </nav>
      </header>
 
 {/* main component */}
      <main className={styles.main}>
  

<div>
<a href="">
<img/>
<h2>
  Events in london
</h2>

<p>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. 
  Voluptatem hic atque ducimus voluptatum eligendi totam nesciunt dolorem sequi, repellendus doloribus autem? Nobis, eveniet commodi nesciunt vitae perspiciatis exercitationem, hic voluptatem aliquid pariatur eaque fugiat id soluta facilis laudantium ad saepe.
</p>
</a>
          {/* Event in barcelona */}


          <a href="">
            <img />
            <h2>
              Events in Barcelona
            </h2>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatem hic atque ducimus voluptatum eligendi totam nesciunt dolorem sequi, repellendus doloribus autem? Nobis, eveniet commodi nesciunt vitae perspiciatis exercitationem, hic voluptatem aliquid pariatur eaque fugiat id soluta facilis laudantium ad saepe.
            </p>
          </a>
{/* Event in san fransisco */}
          <a href="">
            <img />
            <h2>
              Events in sab fransisco
            </h2>

            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Voluptatem hic atque ducimus voluptatum eligendi totam nesciunt dolorem sequi, repellendus doloribus autem? Nobis, eveniet commodi nesciunt vitae perspiciatis exercitationem, hic voluptatem aliquid pariatur eaque fugiat id soluta facilis laudantium ad saepe.
            </p>
          </a>

</div>



        <footer className={styles.footer}>
<p>
  @ 2020 Time to code - earn some bucks
</p>

        </footer>
    
      </main>
    
    
    </div>
  )
}
